### ISSUE TITLE
Dialogue buttons have to be clicked twice with the mouse

### ISSUE THREAD

**Issue by LeMoonStar** [1Turtle/consult#4]
When trying to click a button that is not already selected, two clicks are required: one to select the button and another one to actually click it. This is unusual as the majority of GUIs don't work like this. The selection behaviour should however be kept for keyboard input.
The solution should be easy: when clicking a button with the mouse, don't check if it is selected, instead always execute the action associated with it.

**Comment by 1Turtle** [comment]
I will add an option that toggles 1 or 2 required clicks for execution. In newer versions, it will then be on 1 for default.
